[workspace]
authors = ["etvoucsd <89223599+NastyEthan@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "25fa-dsc180a-team2"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]
create-cohort = "python scripts/create_cohort.py"
test-cohort = "python scripts/test_cohort_creation.py"

[dependencies]
python = ">=3.14.0,<3.15"
numpy = ">=2.3.3,<3"
pandas = ">=2.3.3,<3"
scikit-learn = ">=1.7.2,<2"
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.10.6,<4"
seaborn = ">=0.13.2,<0.14"
sqlalchemy = "*"
python-dotenv = "*"
